'use client';
import Image from 'next/image';
import { useEffect, useMemo, useRef, useState } from 'react';
import { AnimatePresence, motion, useReducedMotion, useScroll, useTransform } from 'motion/react';
import Lenis from 'lenis';
import { ArrowRight, ArrowUpRight, Check, ClipboardList, Headphones, Menu, MessageCircle, Minus, Plus, Search, ShieldCheck, ShoppingBag, Trash2, Truck, Wrench, X } from 'lucide-react';
import { company } from '@/config/company';
import { products } from '@/data/products';
import type { Product, Vehicle } from '@/types/product';

type Cart = Record<string, number>; type Filter = 'Todos' | Vehicle;
const ease = [0.22, 1, 0.36, 1] as const;
function whatsapp(message:string){if(company.whatsapp==='INSERIR_NUMERO_AQUI'){alert('Configure o número do WhatsApp em src/config/company.ts');return}window.open(`https://wa.me/${company.whatsapp}?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer')}
function normalizeSearch(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
function Reveal({children,delay=0,className='',direction='up'}:{children:React.ReactNode;delay?:number;className?:string;direction?:'up'|'left'|'right'}){const reduced=useReducedMotion();const offset=direction==='left'?{x:-28}:direction==='right'?{x:28}:{y:28};return <motion.div className={className} initial={reduced?false:{opacity:0,...offset}} whileInView={{opacity:1,x:0,y:0}} viewport={{once:true,amount:.2}} transition={{duration:.72,delay,ease}}>{children}</motion.div>}
function Button({children,onClick,href,tone='primary',className=''}:{children:React.ReactNode;onClick?:()=>void;href?:string;tone?:'primary'|'secondary'|'light';className?:string}){const content=<>{children}<ArrowUpRight size={16}/></>;return href?<a className={`button ${tone} ${className}`} href={href}>{content}</a>:<button className={`button ${tone} ${className}`} onClick={onClick}>{content}</button>}

export default function Home(){
 const [cart,setCart]=useState<Cart>({}),[drawer,setDrawer]=useState(false),[menu,setMenu]=useState(false),[scrolled,setScrolled]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState<Filter>('Todos'),[added,setAdded]=useState<string|null>(null),[vehicle,setVehicle]=useState(''),[year,setYear]=useState(''),[name,setName]=useState(''),[catalogExpanded,setCatalogExpanded]=useState(false),[mobileCatalog,setMobileCatalog]=useState(false);
 const heroRef=useRef<HTMLElement>(null),reduced=useReducedMotion();const {scrollYProgress}=useScroll({target:heroRef,offset:['start start','end start']});const productY=useTransform(scrollYProgress,[0,1],[0,reduced?0:60]),planeY=useTransform(scrollYProgress,[0,1],[0,reduced?0:28]);
 useEffect(()=>{const saved=localStorage.getItem('central-vans-cart');if(saved)try{setCart(JSON.parse(saved))}catch{}const lenis=new Lenis({duration:1.05,smoothWheel:true});let frame=0;const raf=(time:number)=>{lenis.raf(time);frame=requestAnimationFrame(raf)};frame=requestAnimationFrame(raf);const media=window.matchMedia('(max-width: 700px)');const syncCatalog=()=>setMobileCatalog(media.matches);syncCatalog();const onScroll=()=>setScrolled(window.scrollY>50);window.addEventListener('scroll',onScroll,{passive:true});media.addEventListener('change',syncCatalog);return()=>{cancelAnimationFrame(frame);lenis.destroy();window.removeEventListener('scroll',onScroll);media.removeEventListener('change',syncCatalog)}},[]);
 useEffect(()=>{localStorage.setItem('central-vans-cart',JSON.stringify(cart))},[cart]);useEffect(()=>{document.body.style.overflow=drawer||menu?'hidden':'';return()=>{document.body.style.overflow=''}},[drawer,menu]);
 const count=Object.values(cart).reduce((sum,q)=>sum+q,0);const visible=useMemo(()=>{const terms=normalizeSearch(query).split(/\s+/).filter(Boolean);return products.filter(p=>{const matchesVehicle=filter==='Todos'||p.vehicle===filter;const searchable=normalizeSearch([p.name,p.category,p.description,p.slug,p.vehicle,p.application,...(p.searchTerms??[])].filter(Boolean).join(' '));return matchesVehicle&&terms.every(term=>searchable.includes(term))})},[filter,query]);const catalogIsActive=Boolean(query.trim())||filter!=='Todos';const initialCatalogCount=mobileCatalog?6:8;const displayedProducts=catalogExpanded||catalogIsActive?visible:visible.slice(0,initialCatalogCount);
 const add=(id:string)=>{setCart(c=>({...c,[id]:(c[id]||0)+1}));setAdded(id);window.setTimeout(()=>setAdded(c=>c===id?null:c),1200)};const remove=(id:string)=>setCart(c=>{const n={...c};if(n[id]>1)n[id]--;else delete n[id];return n});
 const sendQuote=()=>{const lines=products.filter(p=>cart[p.id]).map(p=>`• ${cart[p.id]}x ${p.name} — ${p.vehicle??p.application}`).join('\n');whatsapp(`Olá! Vim pelo site da Central Vans e gostaria de solicitar um orçamento.\n\nProdutos selecionados:\n${lines}\n\nVeículo: ${vehicle||'Não informado'}\nAno: ${year||'Não informado'}\nNome: ${name||'Não informado'}\n\nPoderia me informar os valores e a disponibilidade?`)};
 const links=[['Início','#inicio'],['Peças','#produtos'],['Hyundai HR','#linhas'],['Kia Bongo','#linhas'],['Central Vans','#central'],['Contato','#contato']];
 return <main>
  <motion.header className={`site-header ${scrolled?'is-scrolled':''}`} initial={reduced?false:{opacity:0,y:-12}} animate={{opacity:1,y:0}} transition={{duration:.55,ease}}><a className="logo" href="#inicio"><Image src="/brand/central-vans-logo.png" alt="Central Vans" width={460} height={170} priority/></a><nav className="desktop-nav">{links.map(([label,href])=><a key={label} href={href}>{label}</a>)}</nav><div className="header-actions"><button className="header-whatsapp" onClick={()=>whatsapp('Olá! Gostaria de falar com a Central Vans.')}><MessageCircle size={17}/><span>Falar no WhatsApp</span></button><button className="quote-trigger" onClick={()=>setDrawer(true)} aria-label={`Meu orçamento, ${count} itens`}><ClipboardList size={18}/><span>Meu orçamento</span><motion.b key={count} initial={reduced?false:{scale:.6}} animate={{scale:1}}>{count}</motion.b></button><button className="menu-trigger" onClick={()=>setMenu(true)} aria-label="Abrir menu"><Menu/></button></div></motion.header>
  <AnimatePresence>{menu&&<motion.div className="mobile-menu" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><button onClick={()=>setMenu(false)} aria-label="Fechar menu"><X/></button>{links.map(([label,href],i)=><motion.a key={label} href={href} onClick={()=>setMenu(false)} initial={{opacity:0,x:24}} animate={{opacity:1,x:0}} transition={{delay:i*.05}}>{label}</motion.a>)}</motion.div>}</AnimatePresence>
  <section ref={heroRef} id="inicio" className="campaign-hero"><motion.div className="hero-plane" style={{y:planeY}}/><div className="hero-grid"/><div className="hero-content"><motion.p className="technical-label" initial={reduced?false:{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{duration:.65,ease}}>CENTRAL VANS <span>HYUNDAI HR · KIA BONGO</span></motion.p><h1>{['Peças para quem','não pode parar'].map((line,i)=><span className={i?'accent':''} key={line}><motion.i initial={reduced?false:{y:48,opacity:0}} animate={{y:0,opacity:1}} transition={{duration:.78,delay:.1+i*.11,ease}}>{line}</motion.i></span>)}</h1><motion.p className="hero-statement" initial={reduced?false:{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.68,delay:.4,ease}}>Especialistas em peças para Hyundai HR e Kia Bongo, com envio imediato e atendimento direto para encontrar a solução certa para o seu utilitário.</motion.p><div className="hero-actions"><motion.div initial={reduced?false:{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.62,delay:.52,ease}}><Button href="#produtos">Encontrar minha peça</Button></motion.div><motion.div initial={reduced?false:{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.62,delay:.61,ease}}><Button tone="secondary" onClick={()=>whatsapp('Olá! Gostaria de falar com um especialista da Central Vans.')}>Falar com um especialista</Button></motion.div></div></div><motion.div className="hero-machine" style={{y:productY}} initial={reduced?false:{opacity:0,scale:.96,x:32}} animate={{opacity:1,scale:1,x:0}} transition={{duration:.95,delay:.2,ease}}><Image src="/vehicles/hero-hyundai-hr.png" alt="Hyundai HR para trabalho e utilitários" fill priority sizes="(max-width: 800px) 96vw, 55vw"/></motion.div><motion.div className="hero-trust" initial={reduced?false:{opacity:0,y:22}} animate={{opacity:1,y:0}} transition={{duration:.72,delay:.76,ease}}>{[[Truck,'Envio imediato','Agilidade para seu utilitário voltar à rua'],[ShieldCheck,'Peças selecionadas','Qualidade para o seu utilitário'],[Wrench,'Hyundai HR e Kia Bongo','Especialistas em HR e Bongo'],[Headphones,'Atendimento especializado','Contato direto com a equipe']].map(([Icon,title,text])=><div className="trust-item" key={String(title)}><Icon size={21}/><span><b>{String(title)}</b><small>{String(text)}</small></span></div>)}</motion.div></section>
  <section className="search-stage"><Reveal className="search-copy"><span>CATÁLOGO TÉCNICO</span><h2>Encontre sua peça.</h2></Reveal><Reveal delay={.1} className="catalog-search"><Search size={25}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busque alternador, radiador, embreagem..." aria-label="Buscar peça"/><div className="filter-chips">{(['Todos','Hyundai HR','Kia Bongo'] as Filter[]).map(item=><button key={item} className={filter===item?'active':''} onClick={()=>setFilter(item)}>{item}</button>)}</div></Reveal></section>
  <section id="produtos" className="products-stage"><div className="catalog-blueprint" aria-hidden="true">CV / PEÇAS / UTILITÁRIOS</div><div className="stage-heading"><Reveal><span className="index">01 / CATÁLOGO</span><h2>Peças prontas<br/>para rodar.</h2></Reveal><Reveal delay={.1}><p>Componentes selecionados para a rotina de trabalho de quem depende do utilitário todos os dias.</p></Reveal></div><motion.div layout className="editorial-products">{visible.length?<AnimatePresence initial={false}>{displayedProducts.map((p,i)=><ProductCard key={p.id} product={p} index={i} added={added===p.id} onAdd={()=>add(p.id)}/>)}</AnimatePresence>:<div className="no-results"><Search/><h3>Nenhuma peça encontrada</h3><p>Tente outro termo ou consulte nossa equipe.</p></div>}</motion.div>{!catalogIsActive&&visible.length>initialCatalogCount&&<motion.button className="catalog-toggle" onClick={()=>setCatalogExpanded(value=>!value)} initial={{opacity:0,y:14}} whileInView={{opacity:1,y:0}} viewport={{once:true}} aria-expanded={catalogExpanded}>{catalogExpanded?'Mostrar menos':'Ver todas as peças'} <span>{catalogExpanded?'−':'+'}</span></motion.button>}</section>
  <section id="linhas" className="vehicle-stage"><div className="vehicle-heading"><Reveal><span>LINHAS ESPECIALIZADAS</span><h2>Feito para quem trabalha<br/>com <em>HR e Bongo.</em></h2></Reveal></div><div className="vehicle-composition"><Reveal className="vehicle-panel hr-panel" direction="left"><button onClick={()=>{setFilter('Hyundai HR');document.getElementById('produtos')?.scrollIntoView()}}><div className="vehicle-copy"><small>01 · HYUNDAI</small><strong>HR</strong><p>Peças selecionadas para manter sua HR pronta para trabalhar.</p><span>Ver peças <ArrowUpRight/></span></div><VehicleImage src="/vehicles/hyundai-hr.png" alt="Hyundai HR" direction="left"/></button></Reveal><Reveal delay={.12} className="vehicle-panel bongo-panel" direction="right"><button onClick={()=>{setFilter('Kia Bongo');document.getElementById('produtos')?.scrollIntoView()}}><VehicleImage src="/vehicles/kia-bongo.png" alt="Kia Bongo" direction="right"/><div className="vehicle-copy"><small>02 · KIA</small><strong>BONGO</strong><p>Componentes para quem depende do utilitário todos os dias.</p><span>Ver peças <ArrowUpRight/></span></div></button></Reveal></div></section>
  <section id="central" className="brand-stage"><div className="brand-visual"><Reveal direction="left"><Image src="/products/kit-embreagem.png" alt="Kit de embreagem" width={750} height={750} sizes="(max-width: 800px) 90vw, 48vw"/></Reveal><span>PEÇAS / AGILIDADE / CONFIANÇA</span></div><div className="brand-story"><Reveal><p className="technical-label">CENTRAL VANS</p><h2>Mais do que vender peças.<br/><em>Entendemos a rotina</em><br/>do seu utilitário.</h2></Reveal><div className="principles">{[['Qualidade','Peças selecionadas para desempenho e durabilidade.'],['Agilidade','Envio imediato para reduzir o tempo parado.'],['Especialização','Foco nas necessidades de Hyundai HR e Kia Bongo.'],['Atendimento','Contato direto com quem entende do assunto.']].map(([title,text],i)=><Reveal delay={i*.07} key={title}><div className="principle"><b>0{i+1}</b><strong>{title}</strong><p>{text}</p><ArrowRight/></div></Reveal>)}</div></div></section>
  <section id="contato" className="final-cta"><div className="cta-blueprint">HR<br/>BONGO</div><Reveal className="cta-copy"><span>PRECISA DE UMA PEÇA?</span><h2>Seu utilitário precisa<br/>voltar pra rua?</h2><p>Fale com quem entende de Hyundai HR e Kia Bongo e encontre a peça certa com agilidade.</p><Button onClick={()=>whatsapp('Olá! Gostaria de falar com um especialista da Central Vans.')}>Falar com um especialista</Button></Reveal><motion.div className="cta-vehicle" initial={{opacity:0,x:50,scale:.96}} whileInView={{opacity:1,x:0,scale:1}} viewport={{once:true,amount:.2}} transition={{duration:.85,ease}}><Image src="/vehicles/hero-hyundai-hr.png" alt="Hyundai HR Central Vans" fill sizes="(max-width: 700px) 100vw, 48vw"/></motion.div></section>
  <footer><div className="footer-brand"><Image src="/brand/central-vans-logo.png" alt="Central Vans" width={460} height={170}/><p>Peças para vans e utilitários com atendimento especializado.</p></div><div><b>Navegação</b><a href="#inicio">Início</a><a href="#produtos">Peças</a><a href="#central">Central Vans</a><a href="#contato">Contato</a></div><div><b>Linhas</b><a href="#linhas">Hyundai HR</a><a href="#linhas">Kia Bongo</a></div><div><b>Contato</b><button onClick={()=>whatsapp('Olá! Vim pelo site da Central Vans.')}>WhatsApp</button>{company.email !== 'INSERIR_EMAIL_AQUI' && <span>{company.email}</span>}{company.instagram !== 'INSERIR_INSTAGRAM_AQUI' && <span>{company.instagram}</span>}</div><div className="footer-bottom"><small>© 2026 Central Vans. Todos os direitos reservados.</small><span>centralvans.com.br</span></div></footer>
  <button className="floating-whatsapp" onClick={()=>whatsapp('Olá! Vim pelo site da Central Vans.')} aria-label="Falar pelo WhatsApp"><WhatsAppIcon/><i>WhatsApp</i></button>
  <AnimatePresence>{drawer&&<motion.div className="drawer-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setDrawer(false)}><motion.aside className="quote-drawer" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{type:'spring',stiffness:330,damping:34}} onClick={e=>e.stopPropagation()} role="dialog" aria-modal="true" aria-label="Meu orçamento"><button className="drawer-close" onClick={()=>setDrawer(false)} aria-label="Fechar"><X/></button><span className="drawer-label">SELEÇÃO DE PEÇAS</span><h2>Meu orçamento.</h2>{count===0?<div className="empty-quote"><ShoppingBag/><h3>Seu orçamento está vazio</h3><button onClick={()=>setDrawer(false)}>Explorar peças <ArrowRight/></button></div>:<><div className="quote-items">{products.filter(p=>cart[p.id]).map((p,i)=><motion.div className="quote-row" key={p.id} initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} transition={{delay:i*.05}}><Image src={p.image} alt="" width={64} height={64}/><div><b>{p.name}</b><small>{p.vehicle??p.application}</small></div><div className="stepper"><button onClick={()=>remove(p.id)} aria-label="Diminuir"><Minus/></button><span>{cart[p.id]}</span><button onClick={()=>add(p.id)} aria-label="Aumentar"><Plus/></button></div></motion.div>)}</div><div className="quote-form"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Seu nome (opcional)"/><select value={vehicle} onChange={e=>setVehicle(e.target.value)}><option value="">Veículo (opcional)</option><option>Hyundai HR</option><option>Kia Bongo</option><option>Outro</option></select><input value={year} onChange={e=>setYear(e.target.value)} placeholder="Ano do veículo (opcional)"/><Button className="send-quote" onClick={sendQuote}>Solicitar pelo WhatsApp</Button><button className="clear-quote" onClick={()=>setCart({})}><Trash2/> Limpar seleção</button></div></>}</motion.aside></motion.div>}</AnimatePresence>
 </main>
}
function ProductCard({product,index,added,onAdd}:{product:Product;index:number;added:boolean;onAdd:()=>void}){const application=product.vehicle??product.application;const immediate=product.availability.toLowerCase().includes('envio imediato');return <motion.article layout className={`editorial-product product-${index}`} initial={{opacity:0,y:index===0?30:25}} animate={{opacity:1,y:0}} exit={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.16}} transition={{duration:.55,delay:Math.min(index*.1,.4),ease}}><div className="product-media"><span className="product-number">{String(index+1).padStart(2,'0')}</span>{product.id==='alternador'&&<b className="featured-label">Destaque</b>}<Image src={product.image} alt={`${product.name} — ${application}`} fill sizes={index===0?'(max-width: 800px) 92vw, 48vw':'(max-width: 800px) 92vw, 25vw'}/></div><div className="product-meta"><small>{product.category} / {application}</small><h3>{product.name}</h3><p className={`product-status ${immediate?'immediate':'consult'}`}><i/> {immediate?'Envio imediato':'Consulte a aplicação'}</p><button onClick={onAdd}>{added?<><Check/> Adicionado</>:<><Plus/> Adicionar ao orçamento <ArrowUpRight/></>}</button></div></motion.article>}
function VehicleImage({src,alt,direction}:{src:string;alt:string;direction:'left'|'right'}){const reduced=useReducedMotion();const ref=useRef<HTMLDivElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:['start end','end start']});const y=useTransform(scrollYProgress,[0,1],direction==='left'?[12,-12]:[-10,14]);return <motion.div ref={ref} className={`vehicle-image ${direction}`} style={{y}} initial={reduced?false:{opacity:0,scale:.94}} whileInView={{opacity:1,scale:1}} viewport={{once:true,amount:.2}} transition={{duration:.8,ease}}><Image src={src} alt={alt} fill sizes="(max-width: 700px) 100vw, 62vw"/></motion.div>}
function WhatsAppIcon(){return <svg className="whatsapp-icon" viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M12.04 2a9.84 9.84 0 0 0-8.46 14.86L2 22l5.28-1.55A9.94 9.94 0 1 0 12.04 2Zm0 17.99a8.08 8.08 0 0 1-4.12-1.13l-.3-.18-3.13.92.94-3.05-.2-.32a8.13 8.13 0 1 1 6.81 3.76Zm4.46-6.08c-.24-.12-1.44-.71-1.67-.79-.22-.08-.38-.12-.55.12-.16.25-.63.8-.77.96-.14.16-.28.18-.53.06-.24-.12-1.03-.38-1.96-1.21a7.32 7.32 0 0 1-1.36-1.7c-.14-.25-.01-.38.11-.5.11-.11.24-.28.36-.43.12-.14.16-.24.24-.41.08-.16.04-.3-.02-.42-.06-.12-.55-1.32-.75-1.81-.2-.47-.4-.4-.55-.41h-.47c-.16 0-.42.06-.65.3-.22.25-.85.84-.85 2.04s.87 2.36.99 2.52c.12.16 1.72 2.63 4.17 3.69.58.25 1.04.4 1.39.51.59.19 1.12.16 1.54.1.47-.07 1.44-.59 1.65-1.16.2-.57.2-1.06.14-1.16-.06-.1-.22-.16-.47-.29Z"/></svg>}
